import Head from 'next/head'
import styles from '@/styles/index.module.css'
import { ProjectSchemas } from "@/utils/ProjectsLinks"
import Router from 'next/router'
import { useState } from 'react'
export default function Home() {

  const projectSchema = ProjectSchemas()
  const [projectList, setProjectlist] = useState(projectSchema)


  return (
    <>
      <Head>
        <title>Css Studie Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} >

        <div className={styles.app}>

          <div className={styles.header}>

            <div className={styles.circleArea}>
              <div className={styles.redCircle} />
              <div className={styles.yellowCircle} />
              <div className={styles.greenCircle} />
            </div>

            <h1>My css study project</h1>
          </div>

          <div className={styles.AppArea}>
            <div className={styles.AppBox}>
              {
                projectList.map((project, index) => {
                  return (
                    <div className={styles.listObject} key={index} onClick={() => Router.push(project.link)}>
                      <h1>

                        {project.name}
                      </h1>
                      <h2>

                        {project.description}
                      </h2>
                      {project.icon}

                    </div>)
                })
              }
            </div>
          </div>

        </div>

      </main>
    </>
  )
}
